include:
  - compose-base.yaml

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    expose:
      - 8080
      - 8443
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: http://localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;" ]
      interval: 10s
      timeout: 10s
      retries: 20
    command:
      - start
      - --import-realm
    volumes:
      - /home/ubuntu/keycloak-export/bluecore-realm.json:/opt/keycloak/data/import/realm.json
      - /home/ubuntu/keycloak-export:/opt/keycloak/data/export


  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "443:80"
    depends_on:
      - keycloak
      - airflow-webserver
