include:
  - compose-base.yaml

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    expose:
      - 8080
      - 8443
    env_file:
      - ./.env
    command:
      - start

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "443:80"
    depends_on:
      - keycloak
      - airflow-webserver
